#!/usr/bin/env python3
"""Sensitivity check: does treating multi-character EVA sequences as single
atomic glyphs (rather than separate characters) change the character-level
entropy/constraint-ratio findings from statistician_pass1.py and
language_baselines.py?

Background: EVA (European Voynich Alphabet) is a transliteration convention,
not the manuscript's actual script. Several EVA digraphs/trigraphs are
widely treated in the Voynich research literature as representing a single
handwritten stroke or glyph in the original manuscript, not two or three
independent letters -- most commonly "ch", "sh", and the four "gallows +
bench" combinations "ckh", "cth", "cph", "cfh". Treating them as separate
characters (as statistician_pass1.py and language_baselines.py both do,
for simplicity) may be undercounting the manuscript's real character-level
structure, since a single stroke is being split into 2-3 "characters" that
always co-occur.

This is NOT a claim of consensus. Other candidate atomic groupings exist in
the literature (e.g. "qo-" clustering, "in"/"ii"/"iii" minim-group clustering)
and are deliberately NOT included here -- they are more contested and left
as a further extension, named explicitly in the output rather than silently
assumed. This script implements exactly one reasonable, commonly-cited
atomic-glyph policy and reports what changes and what doesn't.

Usage:
    python3 atomic_eva_glyphs.py

Reads:  data/derived/ZL3b-normalized.txt
Writes: data/derived/atomic-eva-glyphs-report.md
        data/derived/atomic-eva-glyphs-summary.json
"""

import json
import math
import re
from collections import Counter
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
NORMALIZED = REPO_ROOT / "data" / "derived" / "ZL3b-normalized.txt"
OUT_REPORT = REPO_ROOT / "data" / "derived" / "atomic-eva-glyphs-report.md"
OUT_SUMMARY = REPO_ROOT / "data" / "derived" / "atomic-eva-glyphs-summary.json"

# Longest-match-first: multi-character atomic glyphs, then fall back to any
# single remaining character. Order matters -- regex alternation is
# left-to-right, not automatically longest-match, so longer sequences are
# listed first.
ATOMIC_MULTI = ["ckh", "cth", "cph", "cfh", "ch", "sh"]
GLYPH_PATTERN = re.compile("|".join(ATOMIC_MULTI) + "|.")

CHAR_LEVEL_CONSTRAINT_REFERENCE = 0.4539  # from statistician-pass1-summary.json / language-baselines-summary.json, Voynich overall


def load_words():
    words = []
    with NORMALIZED.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.rstrip("\n")
            if not line:
                continue
            _locus, text = line.split("\t", 1)
            if text:
                words.extend(text.split(" "))
    return words


def tokenize_glyphs(word):
    return GLYPH_PATTERN.findall(word)


def shannon_entropy(counter):
    total = sum(counter.values())
    if total == 0:
        return 0.0
    ent = 0.0
    for c in counter.values():
        p = c / total
        ent -= p * math.log2(p)
    return ent


def glyph_bigram_conditional_entropy(glyph_words):
    pair_counts = Counter()
    prefix_counts = Counter()
    for glyphs in glyph_words:
        for i in range(1, len(glyphs)):
            prefix, nxt = glyphs[i - 1], glyphs[i]
            pair_counts[(prefix, nxt)] += 1
            prefix_counts[prefix] += 1
    total = sum(pair_counts.values())
    if total == 0:
        return 0.0
    h = 0.0
    for (prefix, nxt), c in pair_counts.items():
        p_joint = c / total
        p_cond = c / prefix_counts[prefix]
        h -= p_joint * math.log2(p_cond)
    return h


def main():
    words = load_words()
    glyph_words = [tokenize_glyphs(w) for w in words]
    all_glyphs = [g for gw in glyph_words for g in gw]

    glyph_counts = Counter(all_glyphs)
    h1 = shannon_entropy(glyph_counts)
    h2 = glyph_bigram_conditional_entropy(glyph_words)
    constraint = round(1 - (h2 / h1), 4) if h1 else None

    multi_char_glyph_uses = sum(1 for g in all_glyphs if len(g) > 1)

    report = [
        "# Atomic EVA Glyph Sensitivity Check",
        "",
        "Generated by `data/scripts/atomic_eva_glyphs.py`. Tests whether treating "
        f"{', '.join(f'`{g}`' for g in ATOMIC_MULTI)} as single atomic glyphs, "
        "instead of 2-3 separate characters, changes the character-level constraint "
        "finding from `statistician_pass1.py` / `language_baselines.py`.",
        "",
        "**Not a claim of consensus.** This is one commonly-cited atomic-glyph grouping "
        "from the Voynich research literature, not the only one proposed. Deliberately "
        "NOT implemented here: `qo-` clustering, and `in`/`ii`/`iii` minim-group "
        "clustering -- both more contested, left as further extensions.",
        "",
        "## Method",
        "",
        f"Same source as pass 1: `data/derived/ZL3b-normalized.txt` ({len(words):,} tokens, "
        "already downstream of the normalize_eva.py first-option-kept policy -- that "
        "caveat still applies here unchanged). Each word is tokenized greedily, longest "
        f"match first, against the atomic set `{ATOMIC_MULTI}`, falling back to single "
        "characters for everything else. Entropy (H1) and bigram conditional entropy "
        "(H2) are computed over the resulting glyph-token sequences, exactly analogous "
        "to the character-level calculation in `statistician_pass1.py` but with glyphs "
        "as the unit instead of characters.",
        "",
        "## Results",
        "",
        f"- Character-level constraint ratio (reference, from existing Confirmed Findings): **{CHAR_LEVEL_CONSTRAINT_REFERENCE}**",
        f"- Atomic-glyph-level constraint ratio: **{constraint}**",
        f"- Glyph alphabet size: {len(glyph_counts)} (vs. 42 literal characters in the pass-1 alphabet)",
        f"- Total glyph tokens: {len(all_glyphs):,} (vs. {sum(len(w) for w in words):,} literal characters)",
        f"- Atomic multi-character glyph occurrences: {multi_char_glyph_uses:,} ({multi_char_glyph_uses / len(all_glyphs) * 100:.1f}% of all glyph tokens)",
        f"- Glyph-level H1: {h1:.4f} bits, H2: {h2:.4f} bits",
        "",
        "## Interpretation (numbers and method only, no meaning claims)",
        "",
        (
            "- If the atomic-glyph constraint ratio is close to the character-level one, "
            "the earlier finding is not an artifact of splitting single strokes into "
            "multiple characters. If it moves substantially, the character-level pass-1 "
            "and language-baseline results need the atomic-glyph version reported "
            "alongside them, not instead of them, since both representations are used "
            "in the literature."
        ),
        (
            "- This check only changes how the Voynich side of the comparison is "
            "tokenized. It does not re-run the language baselines, which remain "
            "character-level for Latin/Italian since those languages don't have the "
            "same multi-character-single-stroke question. A fully fair atomic-vs-atomic "
            "comparison isn't possible across scripts this different -- flagged, not solved."
        ),
        (
            "- `qo-` and minim-group (`in`/`ii`/`iii`) clustering remain unimplemented "
            "and are a real next step if this check shows atomic tokenization matters."
        ),
    ]
    OUT_REPORT.write_text("\n".join(report) + "\n", encoding="utf-8")

    summary = {
        "atomic_glyph_set": ATOMIC_MULTI,
        "not_implemented": ["qo- clustering", "in/ii/iii minim-group clustering"],
        "source": "data/derived/ZL3b-normalized.txt",
        "char_level_constraint_reference": CHAR_LEVEL_CONSTRAINT_REFERENCE,
        "glyph_level_constraint_ratio": constraint,
        "glyph_alphabet_size": len(glyph_counts),
        "total_glyph_tokens": len(all_glyphs),
        "multi_char_glyph_occurrences": multi_char_glyph_uses,
        "glyph_h1_bits": round(h1, 4),
        "glyph_h2_bits": round(h2, 4),
    }
    OUT_SUMMARY.write_text(json.dumps(summary, indent=2) + "\n", encoding="utf-8")

    print(f"Wrote {OUT_REPORT}")
    print(f"Wrote {OUT_SUMMARY}")
    print(f"Char-level constraint: {CHAR_LEVEL_CONSTRAINT_REFERENCE} | Glyph-level constraint: {constraint}")


if __name__ == "__main__":
    main()
