#!/usr/bin/env python3
"""
Normalize the archival ZL3b IVTFF transcription (data/ZL3b-n.txt) into a
word-tokenized corpus for statistical analysis, without silently discarding
the ambiguity present in the source.

Every non-trivial resolution this script makes (alternative-reading choice,
drawing-intrusion word break, stripped markup) is recorded in the companion
ambiguity report, keyed by locus tag, so any downstream statistical result
can be traced back to the exact editorial decision that produced it.

Known limitation: this parser was written against empirical inspection of
a sample of ZL3b-n.txt, not the full formal IVTFF grammar spec. It has not
been validated against every edge case the format allows. Treat its output
as a reasonable working corpus, not a definitive transliteration -- see the
report's "Unparsed lines" section for anything it could not confidently
handle, and review before treating downstream stats as final.

Usage:
    python3 normalize_eva.py

Reads:  data/ZL3b-n.txt
Writes: data/derived/ZL3b-normalized.txt
        data/derived/ZL3b-normalization-report.md
"""

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SOURCE = REPO_ROOT / "data" / "ZL3b-n.txt"
OUT_DIR = REPO_ROOT / "data" / "derived"
OUT_TEXT = OUT_DIR / "ZL3b-normalized.txt"
OUT_REPORT = OUT_DIR / "ZL3b-normalization-report.md"

LOCUS_LINE = re.compile(r'^<(f[^,>]+,[^>]+)>\s+(.*)$')
ALT_READING = re.compile(r'\[([^\]:]*):([^\]]*)\]')
INLINE_MARKUP = re.compile(r'<[^>]*>')


def strip_locus_tag(line):
    m = LOCUS_LINE.match(line)
    if not m:
        return None
    return m.group(1), m.group(2)


def resolve_alt_readings(text, locus, report):
    def repl(m):
        first, alt = m.group(1), m.group(2)
        report['alt_readings'].append((locus, first, alt))
        return first
    return ALT_READING.sub(repl, text)


def handle_drawing_intrusion(text, locus, report):
    if '<->' in text:
        report['drawing_intrusions'].append(locus)
    return text.replace('<->', ' ')


def handle_illegible(text, locus, report):
    count = text.count('?')
    if count:
        report['illegible_chars'].append((locus, count))
    return text


def strip_markup(text, locus, report):
    def repl(m):
        report['stripped_markup'].append((locus, m.group(0)))
        return ''
    return INLINE_MARKUP.sub(repl, text)


def tokenize(text):
    # '.' = word separator, ',' = uncertain word space (also a boundary
    # here, but counted separately -- not silently treated as certain)
    words = re.split(r'[.,]', text)
    return [w for w in words if w]


def main():
    if not SOURCE.exists():
        print(f"Source not found: {SOURCE}", file=sys.stderr)
        sys.exit(1)

    report = {
        'alt_readings': [],
        'stripped_markup': [],
        'drawing_intrusions': [],
        'illegible_chars': [],
        'uncertain_spaces': 0,
        'unparsed_lines': [],
        'loci_parsed': 0,
        'words_emitted': 0,
    }

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    out_lines = []

    with SOURCE.open('r', encoding='utf-8') as f:
        for raw_line in f:
            line = raw_line.rstrip('\n')
            if not line or line.startswith('#'):
                continue
            parsed = strip_locus_tag(line)
            if parsed is None:
                if line.startswith('<f'):
                    # Page/paragraph-level header (e.g. "<f1r>  <! $Q=A ...>"),
                    # not a transcription locus -- expected, not an error.
                    continue
                report['unparsed_lines'].append(line)
                continue

            locus, text = parsed
            report['uncertain_spaces'] += text.count(',')
            text = resolve_alt_readings(text, locus, report)
            text = handle_drawing_intrusion(text, locus, report)
            text = handle_illegible(text, locus, report)
            text = strip_markup(text, locus, report)

            words = tokenize(text)
            report['loci_parsed'] += 1
            report['words_emitted'] += len(words)
            out_lines.append(f"{locus}\t{' '.join(words)}")

    OUT_TEXT.write_text('\n'.join(out_lines) + '\n', encoding='utf-8')

    with OUT_REPORT.open('w', encoding='utf-8') as f:
        f.write("# ZL3b Normalization Report\n\n")
        f.write("Generated by `data/scripts/normalize_eva.py` from `data/ZL3b-n.txt`. Re-run the script to reproduce exactly.\n\n")
        f.write(f"- Loci parsed: {report['loci_parsed']}\n")
        f.write(f"- Words emitted: {report['words_emitted']}\n")
        f.write(f"- Alternative readings resolved (first option kept): {len(report['alt_readings'])}\n")
        f.write(f"- Uncertain word-spaces (',') treated as word boundaries: {report['uncertain_spaces']}\n")
        f.write(f"- Drawing intrusions ('<->') treated as word boundaries: {len(report['drawing_intrusions'])}\n")
        f.write(f"- Illegible-character loci ('?'): {len(report['illegible_chars'])}\n")
        f.write(f"- Inline markup tokens stripped: {len(report['stripped_markup'])}\n")
        f.write(f"- Unparsed non-comment lines: {len(report['unparsed_lines'])}\n\n")

        f.write("## Policy (read before trusting any downstream statistic)\n\n")
        f.write("- Alternative reading `[x:y]` -> **first option `x` kept**, both logged below. This is a real editorial choice, not a neutral default -- re-running with `y` kept instead would be an equally legitimate corpus for comparison, not yet built. Any statistical result sensitive to this choice should be re-checked against a `y`-kept variant before being trusted.\n")
        f.write("- `,` (uncertain word space) -> treated as a word boundary, same as `.`, but counted separately so analyses can exclude these loci if word-boundary certainty matters.\n")
        f.write("- `<->` (drawing intrusion) -> treated as a word boundary (text on either side was not contiguous in the source manuscript).\n")
        f.write("- `?` (illegible character) -> left in place as a literal `?` in the token, not stripped or replaced. This means a word containing `?` will not match its otherwise-identical counterpart elsewhere in frequency counts -- flag for the Statistician before running word-frequency stats.\n")
        f.write("- Inline markup (`<%>`, `<!@NNN;>`, `<$>`, extended-Eva `@NNN;` escape codes, etc.) -> stripped entirely; these are editorial/rendering annotations, not glyphs.\n")
        f.write("- Ligature/grouped glyphs (`{...}`) -> left intact as part of the token, not split into components.\n\n")

        if report['alt_readings']:
            f.write(f"## Alternative readings resolved ({len(report['alt_readings'])} total, first 50 shown)\n\n")
            f.write("| Locus | Kept | Alternative |\n|---|---|---|\n")
            for locus, first, alt in report['alt_readings'][:50]:
                f.write(f"| {locus} | `{first}` | `{alt}` |\n")
            f.write("\n")

        if report['unparsed_lines']:
            f.write(f"## Unparsed lines ({len(report['unparsed_lines'])})\n\n")
            f.write("Not comments, not recognized page headers, did not match the expected locus-line pattern. Needs manual review before the corpus can be considered complete.\n\n")
            for line in report['unparsed_lines'][:50]:
                f.write(f"- `{line}`\n")

    print(f"Parsed {report['loci_parsed']} loci, {report['words_emitted']} words.")
    print(f"Alt readings resolved: {len(report['alt_readings'])}")
    print(f"Unparsed lines: {len(report['unparsed_lines'])}")
    print(f"Wrote {OUT_TEXT}")
    print(f"Wrote {OUT_REPORT}")


if __name__ == '__main__':
    main()
